apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-dgl5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-dgl5
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-dgl5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-dgl5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-dgl5
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uhjl-tenant/rhtap-demo-app/hacbs-test-project-dgl5@sha256:882df0ce7277d58a31d1f3b398b27968d565c04b7ae3ffebc6b4c6fffc7ebbea
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
